/**:
  ros__parameters:
    color_range_list:
      Black:
        max:
        - 104
        - 135
        - 137
        min:
        - 0
        - 0
        - 0
      blue:
        max:
        - 90
        - 149
        - 113
        min:
        - 11
        - 115
        - 0
      green:
        max:
        - 76
        - 118
        - 170
        min:
        - 6
        - 99
        - 61
      red:
        max:
        - 55
        - 255
        - 255
        min:
        - 0
        - 140
        - 131
      tennis:
        max:
        - 210
        - 159
        - 255
        min:
        - 31
        - 66
        - 178
      white:
        max:
        - 255
        - 155
        - 155
        min:
        - 106
        - 100
        - 100
      yellow:
        max:
        - 173
        - 159
        - 190
        min:
        - 0
        - 125
        - 169
