/**:
  ros__parameters:
    aggression: 1.3
    approach_dwell: 0.1
    compliance_grasp_enabled: false
    count_move_threshold: 8
    count_still_threshold: 4
    debug: false
    detection_avg_frames: 3
    enable_camera_sub: true
    enable_inference: true
    engine_path: /home/ubuntu/third_party_ros2/data/scaff_cubes_obb_v2.engine
    grab_depth: 0.02
    grasp_max_temp: 65
    grasp_stall_pulse: 8
    grasp_step_dwell: 0.1
    grasp_step_pulse: 15
    grasp_strength: '{}'
    grasp_timeout: 2.0
    gripper_close_duration: 0.35
    gripper_close_pulse: 540
    gripper_open_pulse: 200
    gripper_settle: 0.5
    hot_log_inference_ms: false
    hover_height: 0.06
    inference_max_hz: 0.0
    inference_warmup: true
    lock_distance_thresh: 0.005
    motion_speed: 1.5
    parallel_base_motion: true
    place_positions: '{}'
    publish_jpeg_quality: 80
    publish_max_hz: 0.0
    publish_scale: 1.0
    startup_self_calibrate: true
    target_overrides: '{}'
    test_grip_dwell: 3.0
    yolo_conf_thresh: 0.689943342776204
    yolo_enabled_classes: '[]'
    yolo_iou_thresh: 0.7
    yolo_max_det: 100
